### ISSUE TITLE
Gtk layer shell windows dispear on suspend on hyprland

### ISSUE THREAD

**Issue by godalming123** [wmww/gtk-layer-shell#135]
If I suspend my computer and then open it my python bar hides theres no error message in the terminal I use to run it. Source code at: https://github.com/godalming123/hyprland-panel

**Comment by godalming123** [comment]
This also only happens when I suspend for a while.

**Comment by wmww** [comment]
Strange. Does the program exit, or is the panel just hidden? Does the GTK Layer Shell demo have this problem? Do layer shell clients that don't use GTK Layer Shell also have this problem? A Wayland debug log might be helpful. You can generate that by running
```
WAYLAND_DEBUG=1 <your-program> 2>log.txt
```
That should dump all the Wayland messages to a file. If you upload the whole log that ends with the panel disappearing I can take a look.

**Comment by godalming123** [comment]
1. No the program is still running in the background without an error.

**Comment by godalming123** [comment]
This is the logfile
[test.log](https://github.com/wmww/gtk-layer-shell/files/9550709/test.log)

**Comment by godalming123** [comment]
Does it have anything to do with the fact that my monitor turns off this means when my laptop comes out from suspend all the windows appear on my laptop screen before going to the monitor. Will try with bar on my laptop monitor and turning monitor on before opening laptop.

**Comment by wmww** [comment]
I see from the log that the 2nd of two wl_outputs is being removed and then quickly re-added (presumably because of how your monitor is turning off). It seems likely that that's related, but I see no evidence that the issue is on GTK Layer Shell's side. Next step is to test with a non-GTK client that uses Layer Shell (maybe swaybar?). If the issue exists with that too, than it's the compositor's problem.

**Comment by godalming123** [comment]
Will test

**Comment by godalming123** [comment]
Do you know any sway bar alternatives since sway bar is not in my repos

**Comment by wmww** [comment]
Swaybar might come with the sway package, but it might not want to run on something other than sway. If you build wlroots you'll get a `layer-shell` example, which should work. That might also be available in your repos (`libwlroots-examples` on Ubuntu). Run that with
```
/usr/lib/wlroots/layer-shell -l top -a top
```
(adjust path as needed)

**Comment by ErikReider** [comment]
> Do you know any sway bar alternatives since sway bar is not in my repos

Waybar is a good one

**Comment by wmww** [comment]
Nope, [Waybar uses GTK Layer Shell](https://github.com/Alexays/Waybar/blob/e58f1fd3e083659024ce2cc5481784851f13567e/meson.build#L115)

**Comment by godalming123** [comment]
Tested with yambar (written in c I think using the layer shell protocol without gtk) and it also hides on suspend so I think the issue is to do with hyprland

**Comment by wmww** [comment]
Closing for now, feel free to open new issues for future relevant bugs.

**Comment by godalming123** [comment]
Thanks for your help

**Comment by andrewbaxter** [comment]
Hey! I know I'm a bit late here, but I think I'm hitting the same issue but on sway. Similar situation: bar with gtk layer shell, disappears after swayidle sets dpms off on the screen.

I've attached monitor added/removed events and indeed the monitor seems to disappear when the screen blanks.  In my case, I do `set_monitor` when the monitor comes back and the window reappears... with about 50% probability.

Reading the linked issue, it sounds like all the resources need to be recreated when monitors disappear/reappear.  I feel like that's something either gtk or (this) should do when set_monitor is called.  Maybe the new monitor has the same id as the old monitor and the code thinks it's a no-op?

Otherwise I might be able to shut down, then reinitialize the program when the screen comes back.

**Comment by wmww** [comment]
Neither this library nor the GTK4 version watch for monitor changes. They either use the monitor requested by the app or else pass null through to the compositor. It looks like (at least for me on sway) when a wl_output is removed and re-added it gets both a new `wl_output` Wayland object and a new `GdkMonitor`. Correlating these with previously connected monitors may be possible, but that's out of scope for the library.

The app chose the monitor to display on, and so the app is responsible for updating the monitor if that changes. The one exception might be to automatically change the monitor to null if the one it was set for goes away. Might do this in the GTK4 version but likely not here (project in maintenance mode)

**Comment by wmww** [comment]
Maybe try setting the layer window's monitor to null immediately before setting it to what you want it to be? If the monitor changed check was the thing that was failing that should fix it.

**Comment by andrewbaxter** [comment]
Ah thanks, yeah I was thinking of that.  `set_monitor` doesn't allow `None` in https://github.com/pentamassiv/gtk-layer-shell-gir either and that's archived.  But IIUC though it should just do the same as `set_namespace` (remap?) which I tried with no success.

**Comment by andrewbaxter** [comment]
Just leaving some notes here for next time I come back:
1. After un-blanking, the `Monitor` gtk returns has model NULL and manufacturer NULL
2. After un-blanking, the monitor comes back once, immediately gets disconnected again, then comes back again (also with NULL/NULL)
3. Launching a fresh instance immediately after unblanking didn't fix the issue.  IIRC the last log message was about the monitor getting disconnected, so I think in this case it probably happend in the middle of (2.)...

I added a delay, but I'm not sure I ever fully tested the "exit on disconnect" thing. I should remove the delay and re-test.

IIRC I had to do `set_monitor` because the window wouldn't appear at all if I didn't.  Of course, normal non-layer-shell gtk applications have no problem, which is why I ruled out both sway/wlroots and gtk.  I want to try again without setting monitor at all and see if that changes anything.

**Comment by andrewbaxter** [comment]
Okay I just tried gtk4-layer-shell on another gtk4 project had with (again) a window in the overlay layer. When the screen blanked and came back, the window was gone.  The gui application was still running, and the bg process that was waiting for the fg input had hung.

So a quick summary
- Issue on gtk3 + gtk4
- Issue in hyprland and sway
- Remapping window doesn't help(?)
- The only workaround seems to be closing the application on display-off and bringing it back on display-on. Hyprland kind of suggests this too per the linked issue (the sufaces are destroyed, so it's necessary for the application to recreate everything).  But that is fairly disruptive to in-progress operations.

To reiterate, I feel like this shouldn't be the application's resposibility to solve, but I'm not sure if this is a layer shell, compositor, wlroots, or gtk issue.  My gut feeling is that the surface destruction isn't being communicated or detected at some layer.

**Comment by wmww** [comment]
Ok there's definitely some problems. One is that I assumed if a layer surface did not set an output Sway would keep it displayed. This doesn't seem to be the case. Looking into it.

**Comment by wmww** [comment]
#198 should address this. Please try it out if anybody gets a chance, and make sure it doesn't break anything I haven't noticed.
